[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip"
]

[variables]
# Playwright'ın tarayıcıları varsayılan dizine kurması için bu değişkeni boş bırakabiliriz
# veya tamamen silebiliriz. Sorun çıkarırsa standart yolda çalışması en iyisidir.

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt",
  "python -m playwright install --with-deps chromium"
]

[start]
cmd = "python is_ilani_takip.py"