[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "nss",
  "nspr",
  "atk",
  "at-spi2-atk",
  "cups",
  "dbus",
  "drm",
  "expat",
  "libxkbcommon",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "mesa",
  "gtk3",
  "pango",
  "cairo",
  "alsa-lib"
]

[variables]
PLAYWRIGHT_BROWSERS_PATH = "0"

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt",
  "python -m playwright install chromium"
]

[start]
cmd = "python -m playwright install chromium && python is_ilani_takip.py"
